### PR TITLE
Packt readme

### PR DESCRIPTION
**Pull request by brucevanhorn2**
Jubit asked me to change the README.md file to match the style used at https://github.com/PacktPublishing/Deciphering-Object-Oriented-Programming-with-CPP/blob/main/README.md.  This represents my attempt.

### CODE REVIEW

**Comment by brucevanhorn2** [comment]
I don't have the URL for the book on Packt's web site so I used my web site for the link.  Furthermore, I don't have the URL to the book's preview image on Packt's CDN, so the image is linked to my own CDN, however the image itself is in the repo under the readme-assets folder.

**Review by Jubit-packt — CHANGES_REQUESTED** [review]
# Real-World Implementation of C# Design Patterns

<a href="https://www.amazon.com/dp/1803242736">Real-World Implementation of C# Design Patterns</a>

This is the code repository for [Real-World Implementation of C# Design Patterns](https://www.amazon.com/dp/1803242736), published by Packt.

**Overcome daily programming challenges using elements of reusable object-oriented software**

## What is this book about?
As a software developer, you need to learn new languages and simultaneously get familiarized with the programming paradigms and methods of leveraging patterns, as both a communications tool and an advantage when designing well-written, easy-to-maintain code. Design patterns, being a collection of best practices, provide the necessary wisdom to help you overcome common sets of challenges in object-oriented design and programming.

This book covers the following exciting features:
* Get to grips with patterns, and discover how to conceive and document them
* Explore common patterns that may come up in your everyday work
* Recognize common anti-patterns early in the process
* Use creational patterns to create flexible and robust object structures
* Enhance class designs with structural patterns
* Simplify object interaction and behavior with behavioral patterns

If you feel this book is for you, get your [copy](https://www.amazon.com/dp/1803242736) today!

<a href="https://www.packtpub.com/?utm_source=github&utm_medium=banner&utm_campaign=GitHubBanner">https://www.packtpub.com/</a>

## Instructions and Navigations
All of the code is organized into folders. For example, Chapter02.

The code will look like the following:
```
public interface IBicycleProduct
{
 public IFrame Frame { get; set; }
 public ISuspension Suspension { get; set; }
 public IHandlebars Handlebars { get; set; }
 public IDrivetrain Drivetrain { get; set; }
 public ISeat Seat { get; set; }
 public IBrakes Brakes { get; set; }
}
```

**Following is what you need for this book:**
This book is for beginner and mid-level software developers who are looking to take their object-oriented programs or software designing skills to the next level by learning to leverage common patterns. A firm grasp of programming fundamentals and classical object-oriented programming (OOP) using languages like C#, C++, Objective-C, or Java is expected.

With the following software and hardware list you can run all code files present in the book (Chapter 1-10).
### Software and Hardware List
| Chapter | Software required | OS required |
| -------- | ------------------------------------ | ----------------------------------- |
| 1-10 | C# 10 | Windows |
| 1-10 | .NET Core 6 | Windows |
| 1-10 | Rider, Visual Studio, or Visual Studio Code | Windows |


We also provide a PDF file that has color images of the screenshots/diagrams used in this book. [Click here to download it](https://packt.link/3KWzG).

### Related products
* Parallel Programming and Concurrency with C# 10 and .NET 6 [[Packt]](https://www.packtpub.com/product/parallel-programming-and-concurrency-with-c-10-and-net6/9781803243672?utm_source=github&utm_medium=repository&utm_campaign=9781803243672) [[Amazon]](https://www.amazon.com/dp/1803243678)

* High-Performance Programming in C# and .NET [[Packt]](https://www.packtpub.com/product/high-performance-programming-in-c-and-net/9781800564718?utm_source=github&utm_medium=repository&utm_campaign=9781800564718) [[Amazon]](https://www.amazon.com/dp/1800564716)


## Get to Know the Author
**Bruce M. Van Horn II**
Bruce has 30 years of software development experience in everything from full-stack web development to desktop apps to video games. He also has 25 years of teaching experience at the college/university level.

**Review by Jubit-packt — APPROVED** [review]
# Real-World Implementation of C# Design Patterns

<a href="https://www.amazon.com/dp/1803242736">Real-World Implementation of C# Design Patterns</a>

This is the code repository for [Real-World Implementation of C# Design Patterns](https://www.amazon.com/dp/1803242736), published by Packt.

**Overcome daily programming challenges using elements of reusable object-oriented software**

## What is this book about?
As a software developer, you need to learn new languages and simultaneously get familiarized with the programming paradigms and methods of leveraging patterns, as both a communications tool and an advantage when designing well-written, easy-to-maintain code. Design patterns, being a collection of best practices, provide the necessary wisdom to help you overcome common sets of challenges in object-oriented design and programming.

This book covers the following exciting features:
* Get to grips with patterns, and discover how to conceive and document them
* Explore common patterns that may come up in your everyday work
* Recognize common anti-patterns early in the process
* Use creational patterns to create flexible and robust object structures
* Enhance class designs with structural patterns
* Simplify object interaction and behavior with behavioral patterns

If you feel this book is for you, get your [copy](https://www.amazon.com/dp/1803242736) today!

<a href="https://www.packtpub.com/?utm_source=github&utm_medium=banner&utm_campaign=GitHubBanner">https://www.packtpub.com/</a>

## Instructions and Navigations
All of the code is organized into folders. For example, Chapter02.

The code will look like the following:
```
public interface IBicycleProduct
{
 public IFrame Frame { get; set; }
 public ISuspension Suspension { get; set; }
 public IHandlebars Handlebars { get; set; }
 public IDrivetrain Drivetrain { get; set; }
 public ISeat Seat { get; set; }
 public IBrakes Brakes { get; set; }
}
```

**Following is what you need for this book:**
This book is for beginner and mid-level software developers who are looking to take their object-oriented programs or software designing skills to the next level by learning to leverage common patterns. A firm grasp of programming fundamentals and classical object-oriented programming (OOP) using languages like C#, C++, Objective-C, or Java is expected.

With the following software and hardware list you can run all code files present in the book (Chapter 1-10).
### Software and Hardware List
| Chapter | Software required | OS required |
| -------- | ------------------------------------ | ----------------------------------- |
| 1-10 | C# 10 | Windows |
| 1-10 | .NET Core 6 | Windows |
| 1-10 | Rider, Visual Studio, or Visual Studio Code | Windows |


We also provide a PDF file that has color images of the screenshots/diagrams used in this book. [Click here to download it](https://packt.link/3KWzG).

### Related products
* Parallel Programming and Concurrency with C# 10 and .NET 6 [[Packt]](https://www.packtpub.com/product/parallel-programming-and-concurrency-with-c-10-and-net6/9781803243672?utm_source=github&utm_medium=repository&utm_campaign=9781803243672) [[Amazon]](https://www.amazon.com/dp/1803243678)

* High-Performance Programming in C# and .NET [[Packt]](https://www.packtpub.com/product/high-performance-programming-in-c-and-net/9781800564718?utm_source=github&utm_medium=repository&utm_campaign=9781800564718) [[Amazon]](https://www.amazon.com/dp/1800564716)


## Get to Know the Author
**Bruce M. Van Horn II**
Bruce has 30 years of software development experience in everything from full-stack web development to desktop apps to video games. He also has 25 years of teaching experience at the college/university level.

**Review by brucevanhorn2 — COMMENTED** [review]
OK

**Pull request merged**
